---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
            exclude: __snapshots__
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
            exclude: ^(docs/assets/.*|assets/.*|benchmark/results/.*)$


    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.1.1
      hooks:
          - id: ruff-format
          - id: ruff
            args: [--fix, --exit-non-zero-on-fix]

    - repo: https://github.com/RobertCraigie/pyright-python
      rev: v1.1.318
      exclude: ^typings/
      hooks:
          - id: pyright

    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.35.0
      hooks:
          - id: markdownlint
          - id: markdownlint-fix

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt

    - repo: https://github.com/dhruvmanila/remove-print-statements
      rev: v0.5.2
      hooks:
          - id: remove-print-statements
            args:
                - --verbose
                - --ignore=tests/conftest.py
                - --ignore=seagoat/utils/debug.py
